# Generated by Django 6.0.3 on 2026-08-23 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_atribuir_gerente_ao_catalogo_existente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsavelRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FechamentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('periodo', models.CharField(choices=[('MANHA', 'Manha'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10)),
                ('pix', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('credito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('debito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('dinheiro', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('houve_retirada', models.BooleanField(default=False)),
                ('valor_retirado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('houve_despesa', models.BooleanField(default=False)),
                ('despesa_descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('despesa_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('houve_desperdicio', models.BooleanField(default=False)),
                ('desperdicio_detalhes', models.TextField(blank=True, null=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_editados', to=settings.AUTH_USER_MODEL)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechamentos_caixa', to='app.loja')),
                ('responsavel_retirada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retiradas', to='app.responsavelretirada')),
            ],
            options={
                'ordering': ['-data', 'loja_id'],
            },
        ),
    ]
