# Generated by Django 6.0.3 on 2026-08-24 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remover_credito_e_debito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=120)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='app.conta')),
            ],
            options={
                'ordering': ['data'],
                'unique_together': {('conta', 'data')},
            },
        ),
    ]
