# Generated by Django 6.0.3 on 2026-08-24 03:37

from django.db import migrations, models


def noite_vira_tarde(apps, schema_editor):
    """Lancamentos antigos marcados como noite passam a contar como tarde.

    O turno deixou de existir; deixar as linhas como estao faria o painel
    mostrar um turno em branco, que nenhum filtro alcanca.
    """
    FechamentoCaixa = apps.get_model("app", "FechamentoCaixa")
    FechamentoCaixa.objects.filter(periodo="NOITE").update(periodo="TARDE")


def nada_a_desfazer(apps, schema_editor):
    """Nao da para saber quais TARDE eram NOITE antes."""


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_feriado_local'),
    ]

    operations = [
        migrations.RunPython(noite_vira_tarde, nada_a_desfazer),
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='periodo',
            field=models.CharField(choices=[('MANHA', 'Manha'), ('TARDE', 'Tarde')], max_length=10),
        ),
    ]
