# Generated by Django 6.0.3 on 2026-08-27 02:39
# Editado a mao: codigo_acesso e unique, mas a tabela ja tem linhas. Um
# AddField direto com unique=True quebraria com mais de uma linha vazia
# colidindo no default "". Por isso: adiciona sem unique, preenche cada
# linha com um codigo de verdade, so depois aperta o unique.
#
# preencher_codigo_acesso usa apps.get_model (modelo historico), NAO
# app.models.Conta. Uma migracao de dados roda contra o schema congelado
# naquele ponto da historia — um migrate do zero (todo `manage.py test` faz
# isso) executa esta migracao antes de qualquer coluna adicionada por uma
# migracao futura existir. Se importassemos o modelo real e uma migracao
# posterior alterasse Conta, esta migracao rodaria o codigo atual contra um
# schema mais antigo e quebraria com "column does not exist". Por isso a
# logica de Conta.gerar_codigo_acesso() esta duplicada aqui a mao, congelada
# no tempo — o custo aceito de uma data migration nao poder chamar metodos
# do modelo real.

import secrets

from django.db import migrations, models

LETRAS_DO_CODIGO = "ABCDEFGHJKLMNPQRSTUVWXYZ"
DIGITOS_DO_CODIGO = "23456789"


def _gerar_codigo_acesso(Conta, conta):
    """Copia congelada de Conta.gerar_codigo_acesso em app/models.py."""
    base = "".join(c for c in conta.nome.upper() if c in LETRAS_DO_CODIGO)
    base = (base + "XXXX")[:4]
    for _ in range(50):
        numero = "".join(secrets.choice(DIGITOS_DO_CODIGO) for _ in range(4))
        codigo = f"{base}-{numero}"
        if not Conta.objects.filter(codigo_acesso=codigo).exclude(pk=conta.pk).exists():
            return codigo
    for _ in range(50):
        letras = "".join(secrets.choice(LETRAS_DO_CODIGO) for _ in range(4))
        numero = "".join(secrets.choice(DIGITOS_DO_CODIGO) for _ in range(4))
        codigo = f"{letras}-{numero}"
        if not Conta.objects.filter(codigo_acesso=codigo).exclude(pk=conta.pk).exists():
            return codigo
    raise RuntimeError("Nao foi possivel gerar um codigo de acesso unico")


def preencher_codigo_acesso(apps, schema_editor):
    Conta = apps.get_model('app', 'Conta')
    for conta in Conta.objects.all():
        conta.codigo_acesso = _gerar_codigo_acesso(Conta, conta)
        conta.save(update_fields=["codigo_acesso"])


def reverter_preenchimento(apps, schema_editor):
    # Nada a fazer: o RemoveField que vem depois (na migracao reversa) ja
    # descarta a coluna.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_remover_turno_da_noite'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='codigo_acesso',
            field=models.CharField(blank=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conta',
            name='fechamentos_por_dia',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Um por dia'), (2, 'Manha e tarde')], default=2),
        ),
        migrations.RunPython(preencher_codigo_acesso, reverter_preenchimento),
        migrations.AlterField(
            model_name='conta',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
