# Generated by Django 6.0.3 on 2026-08-27 02:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_conta_codigo_acesso'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoDoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('apelido', models.CharField(max_length=80)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ultimo_uso_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('revogado_em', models.DateTimeField(blank=True, null=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='app.conta')),
            ],
            options={
                'ordering': ['-ultimo_uso_em'],
            },
        ),
    ]
