# Generated by Django 6.0.3 on 2026-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_dispositivo_do_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentocaixa',
            name='periodo',
            field=models.CharField(choices=[('MANHA', 'Manha'), ('TARDE', 'Tarde'), ('DIA', 'Dia')], max_length=10),
        ),
    ]
