# Generated by Django 6.0.3 on 2026-08-28 04:01

"""A loja perde o login proprio, e os campos que so serviam a ele.

Sai Loja.responsavel (o usuario da loja), Loja.email (que era o username
dele), Loja.telefone_whatsapp (o bot identificando de qual loja vinha o
pedido; o bot saiu na 0036), Loja.tipo e Loja.gerente — este ultimo era o
gerente "dono" da loja, do tempo em que varios gerentes dividiam uma rede.

Todas as cinco colunas estavam VAZIAS em todas as lojas quando isto foi
escrito; conferi antes. Se o seu banco tiver conteudo nelas, tire um dump.

Quem lanca o caixa hoje entra pelo codigo da empresa no aparelho, e a gerente
administra as lojas da empresa dela — nao um subconjunto no nome dela.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_unistock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='email',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='telefone_whatsapp',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='tipo',
        ),
    ]
