# Generated by Django 6.0.3 on 2026-08-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_login_da_loja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsavelretirada',
            options={'ordering': ['conta__nome', 'nome']},
        ),
    ]
