# Generated by Django 6.0.3 on 2026-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_despesa_vira_lancamento_proprio'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
