# Generated by Django 6.0.3 on 2026-09-04 01:59

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_despesa_vira_lancamento_proprio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fechamentocaixa',
            options={'base_manager_name': 'todos', 'default_manager_name': 'todos', 'ordering': ['-data', 'loja_id']},
        ),
        migrations.AlterModelManagers(
            name='fechamentocaixa',
            managers=[
                ('todos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fechamentocaixa',
            name='cancelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_cancelados', to=settings.AUTH_USER_MODEL),
        ),
    ]
