# Generated by Django 6.0.3 on 2026-09-03 21:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_loja_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_despesa', to='app.conta')),
            ],
            options={
                'ordering': ['conta__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ElementoDeDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='app.grupodedespesa')),
            ],
            options={
                'ordering': ['grupo__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cnpj', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=200)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='app.conta')),
                ('elemento_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_sugeridos', to='app.elementodedespesa')),
            ],
            options={
                'ordering': ['conta__nome', 'razao_social'],
                'constraints': [models.UniqueConstraint(fields=('conta', 'cnpj'), name='fornecedor_unico_por_conta')],
            },
        ),
        migrations.AddConstraint(
            model_name='grupodedespesa',
            constraint=models.UniqueConstraint(fields=('conta', 'nome'), name='grupo_de_despesa_unico_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='elementodedespesa',
            constraint=models.UniqueConstraint(fields=('grupo', 'nome'), name='elemento_unico_por_grupo'),
        ),
    ]
