# Generated by Django 6.0.3 on 2026-09-03 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_grupodedespesa_elementodedespesa_fornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('chave', models.CharField(max_length=44, unique=True)),
                ('numero', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=10)),
                ('data_emissao', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xml_bruto', models.TextField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_fiscais', to='app.conta')),
                ('elemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='app.elementodedespesa')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_enviadas', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='app.fornecedor')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_fiscais', to='app.loja')),
            ],
            options={
                'ordering': ['-data_emissao', '-created_at'],
                'indexes': [models.Index(fields=['conta', 'data_emissao'], name='app_notafis_conta_i_aff0ad_idx'), models.Index(fields=['loja', 'data_emissao'], name='app_notafis_loja_id_9f4243_idx')],
            },
        ),
    ]
