# Generated by Django 6.0.3 on 2026-09-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_notafiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='modulo_notas_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
