# Generated by Django 6.0.3 on 2026-09-08 21:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_merge_cancelamento_e_notas'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeSalgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=60)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_de_salgado', to='app.conta')),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Salgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salgados', to='app.categoriadesalgado')),
            ],
            options={
                'ordering': ['categoria__ordem', 'categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Desperdicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desperdicios', to='app.fechamentocaixa')),
                ('salgado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desperdicios', to='app.salgado')),
            ],
            options={
                'ordering': ['-fechamento__data', 'salgado__nome'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriadesalgado',
            constraint=models.UniqueConstraint(fields=('conta', 'nome'), name='categoria_de_salgado_unica_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='salgado',
            constraint=models.UniqueConstraint(fields=('categoria', 'nome'), name='salgado_unico_por_categoria'),
        ),
    ]
