# Generated by Django 6.0.3 on 2026-09-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_catalogo_de_salgados'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='catalogo_ativo',
            field=models.BooleanField(default=True, verbose_name='Usa catálogo de itens'),
        ),
        migrations.AddField(
            model_name='conta',
            name='nome_dos_itens',
            field=models.CharField(default='salgados', help_text='Ex.: salgados, pães, tortas. Aparece no formulário e no catálogo.', max_length=40, verbose_name='Como chama o que vende (plural)'),
        ),
        migrations.AddField(
            model_name='conta',
            name='pergunta_consumo',
            field=models.BooleanField(default=True, verbose_name='Pergunta de consumo'),
        ),
        migrations.AddField(
            model_name='conta',
            name='pergunta_despesa',
            field=models.BooleanField(default=True, verbose_name='Pergunta de despesa'),
        ),
        migrations.AddField(
            model_name='conta',
            name='pergunta_devolucao',
            field=models.BooleanField(default=True, verbose_name='Pergunta de devolução'),
        ),
        migrations.AddField(
            model_name='conta',
            name='pergunta_retirada',
            field=models.BooleanField(default=True, verbose_name='Pergunta de retirada'),
        ),
    ]
