# Generated by Django 6.0.3 on 2026-09-30 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_retirada_por_pessoa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='modulo_banco_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CategoriaDeMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferência'), ('RECEBIMENTO', 'Recebimento')], max_length=15)),
                ('nome', models.CharField(max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('entre_lojas', models.BooleanField(default=False, editable=False)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_de_movimento', to='app.conta')),
            ],
            options={
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('banco', models.CharField(choices=[('SANTANDER', 'Santander'), ('BANCO_DO_BRASIL', 'Banco do Brasil'), ('ITAU', 'Itaú'), ('BRADESCO', 'Bradesco'), ('CAIXA', 'Caixa'), ('INTER', 'Inter'), ('NUBANK', 'Nubank'), ('PICPAY', 'PicPay'), ('OUTRO', 'Outro')], max_length=20)),
                ('agencia', models.CharField(blank=True, max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('apelido', models.CharField(blank=True, max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_bancarias', to='app.loja')),
            ],
            options={
                'ordering': ['loja__nome_loja', 'banco', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ImportacaoDeExtrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('nome_do_arquivo', models.CharField(max_length=255)),
                ('conteudo_bruto', models.TextField()),
                ('novas', models.PositiveIntegerField(default=0)),
                ('repetidas', models.PositiveIntegerField(default=0)),
                ('periodo_de', models.DateField(blank=True, null=True)),
                ('periodo_ate', models.DateField(blank=True, null=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='importacoes', to='app.contabancaria')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extratos_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegraDeClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assinatura', models.CharField(max_length=255)),
                ('entrada', models.BooleanField()),
                ('tipo', models.CharField(choices=[('PAGAMENTO', 'Pagamento'), ('TRANSFERENCIA', 'Transferência'), ('RECEBIMENTO', 'Recebimento')], max_length=15)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.categoriademovimento')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_de_classificacao', to='app.conta')),
                ('elemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='app.elementodedespesa')),
            ],
            options={
                'ordering': ['assinatura'],
            },
        ),
        migrations.CreateModel(
            name='TransacaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('id_do_banco', models.CharField(blank=True, max_length=255)),
                ('chave', models.CharField(max_length=80)),
                ('assinatura', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, choices=[('PAGAMENTO', 'Pagamento'), ('TRANSFERENCIA', 'Transferência'), ('RECEBIMENTO', 'Recebimento')], max_length=15, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='app.categoriademovimento')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes_bancarias', to='app.conta')),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='app.contabancaria')),
                ('elemento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes_bancarias', to='app.elementodedespesa')),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacoes', to='app.importacaodeextrato')),
                ('par', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.transacaobancaria')),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='categoriademovimento',
            constraint=models.UniqueConstraint(fields=('conta', 'tipo', 'nome'), name='categoria_de_movimento_unica_por_conta'),
        ),
        migrations.AddConstraint(
            model_name='contabancaria',
            constraint=models.UniqueConstraint(fields=('loja', 'banco', 'agencia', 'numero'), name='conta_bancaria_unica_por_loja'),
        ),
        migrations.AddConstraint(
            model_name='regradeclassificacao',
            constraint=models.UniqueConstraint(fields=('conta', 'assinatura', 'entrada'), name='regra_unica_por_conta'),
        ),
        migrations.AddIndex(
            model_name='transacaobancaria',
            index=models.Index(fields=['conta', 'data'], name='app_transac_conta_i_6af6f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaobancaria',
            index=models.Index(fields=['conta_bancaria', 'data'], name='app_transac_conta_b_dc5fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='transacaobancaria',
            index=models.Index(fields=['conta', 'assinatura'], name='app_transac_conta_i_4b2184_idx'),
        ),
        migrations.AddConstraint(
            model_name='transacaobancaria',
            constraint=models.UniqueConstraint(fields=('conta_bancaria', 'chave'), name='transacao_unica_por_conta_bancaria'),
        ),
    ]
